### ISSUE TITLE
Remove jessie from supported version or add jessie-backports

### ISSUE THREAD

**Issue by jdvr** [idealista/java-role#29]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

openjdk-8-jre-headless package is not available in Debian Jessie repositories, it should be installed from backports

https://packages.debian.org/jessie-backports/openjdk-8-jre-headless

### Steps to Reproduce

Run role against any Jessie

### Versions

3.0.0

**Comment by dortegau** [comment]
Fixed :)
