### ISSUE TITLE
Better way for Docker image creation

### ISSUE THREAD

**Issue by jnogol** [idealista/java-role#53]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

Now we're using Geerlingguy's Docker images as base image for our Java role's image in Dockerhub. Though they're perfectly fine, the way the images are built is not the best and leaves the container with Ansible and the Java Role installed, when is not necessary at all. So we'll look for creating images without Ansible on them and based on Debian Slim images.

**Comment by dortegau** [comment]
Could 

`CMD ["sleep", "infinity"]`

be used instead of:

`CMD ["tail", "-f", "/dev/null"]`

??
