### ISSUE TITLE
Undefined variable java_open_jdk_version

### ISSUE THREAD

**Issue by amanzanotejon** [idealista/java-role#69]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

Problems with the new version 3.4.0. java_open_jdk_version is required.

### Steps to Reproduce

1. Upgrade to 3.4.0
2. Run playbook

**Expected behavior:** Role would be works with defaults variable as previous version.

**Actual behavior:** undefined variable error is thrown.

**Reproduces how often:** Always

### Versions

3.4.0

**Comment by sorobon** [comment]
Fixed in 3.4.1
